version: "3.8"
services:
  app:
    build: .
    depends_on:
      - mysql
    volumes:
      - .:/django
    restart: on-failure
    expose:
      - '8000'
    env_file:
      - ./.env.prod
    image: app:django
    container_name: django_container
      
    command: gunicorn metrics.wsgi:application --bind 0.0.0.0:8000 --workers 2
    # command: python manage.py runserver 0.0.0.0:8000

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_DATABASE: dinametrics
      MYSQL_USER: dina_user
      MYSQL_PASSWORD: dinametrics@2022*
      MYSQL_ROOT_PASSWORD: paloaltodinamtrics@2022*
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    ports:
        - "3306:3306"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./certbot/conf:/etc/letsencrypt
      # - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot

volumes:
  db:
